// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQO7EbSTMdqoBplTIRdbRCqt6xbIRcfm4',
    appId: '1:899563901706:web:3052ba4ff882dc2bf220f3',
    messagingSenderId: '899563901706',
    projectId: 'homelga',
    authDomain: 'homelga.firebaseapp.com',
    storageBucket: 'homelga.appspot.com',
    measurementId: 'G-23BFP1Q8NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIc4bYCCxzGyD0JnPkh4tTtYjhDOqXqVQ',
    appId: '1:899563901706:android:8315b7293ec63b68f220f3',
    messagingSenderId: '899563901706',
    projectId: 'homelga',
    storageBucket: 'homelga.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOrhxa5ohK7ColRtNszklY1IBrrfnlUk',
    appId: '1:899563901706:ios:d9540d4bc74efa41f220f3',
    messagingSenderId: '899563901706',
    projectId: 'homelga',
    storageBucket: 'homelga.appspot.com',
    iosClientId: '899563901706-2ps5cae67d57e6f069il2hj5h442fve4.apps.googleusercontent.com',
    iosBundleId: 'com.example.homelgaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOrhxa5ohK7ColRtNszklY1IBrrfnlUk',
    appId: '1:899563901706:ios:d9540d4bc74efa41f220f3',
    messagingSenderId: '899563901706',
    projectId: 'homelga',
    storageBucket: 'homelga.appspot.com',
    iosClientId: '899563901706-2ps5cae67d57e6f069il2hj5h442fve4.apps.googleusercontent.com',
    iosBundleId: 'com.example.homelgaApp',
  );
}
